name: anime_app
description: A Crunchyroll-style anime app using Flutter, Hive, API Jikan, and SharedPreferences.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile_placeholder.png
